### PR TITLE
Planner item icon added (fixes #425)

### LINKED ISSUE #425: Select "planneritem" does not have icon,unable to modify WIT after selecting "planneritem"
Select "planneritem" does not have icon,unable to modify WIT after selecting "planneritem"
Steps to reproduce 
- Select planneritme from WIT drop down
- close the detail view 
- click on the same WI where you select "planneritem"
- Try to update WIT , unable to modify it.
screenshot from 2016-12-05 14-19-48

### PR DESCRIPTION
**Pull request by sanbornsen**
Fixes #425

### CODE REVIEW

File: src/app/shared-component/icon/iconmap.ts [hunk 1]
```diff
@@ -9,5 +9,6 @@ export const IconMap = {
     'system.fundamental'       : ['fa', 'fa-bank'],
     'system.experience'        : ['fa', 'fa-map'],
     'system.feature'           : ['fa', 'fa-mouse-pointer'],
-    'system.bug'               : ['fa', 'fa-bug']
+    'system.bug'               : ['fa', 'fa-bug'],
+    'system.planneritem'       : ['fa', 'fa-paint-brush']
```
Comment (SMahil) [inline src/app/shared-component/icon/iconmap.ts]: If there is no icon available , we should add default icon for that

Comment (sanbornsen) [inline src/app/shared-component/icon/iconmap.ts]: I agree. Let me do that for this PR. Thanks.
